-- Initial schema for Task Assistant Bot (Vault23)
-- Generated by Gemini, reviewed and patched by Claude.
-- Patches: added set_updated_at trigger function + triggers on all updated_at tables;
--          added ON DELETE SET NULL for nullable FKs.

-- rollback: see bottom of file

-- =============================================================
-- Extensions
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- =============================================================
-- Utility: auto-update updated_at
-- =============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================
-- Tables (ordered by dependencies)
-- =============================================================

-- Global (no workspace dependency)
CREATE TABLE processed_updates (
    update_id   bigint PRIMARY KEY,
    processed_at timestamptz NOT NULL DEFAULT now()
);

-- Workspaces (root tenant)
CREATE TABLE workspaces (
    id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name           text        NOT NULL,
    status         text        NOT NULL DEFAULT 'trial',
    plan           text        NOT NULL DEFAULT 'free',
    trial_ends_at  timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_workspaces_updated_at
  BEFORE UPDATE ON workspaces
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Users
CREATE TABLE users (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id     uuid        NOT NULL REFERENCES workspaces(id),
    display_name     text,
    language         text        NOT NULL DEFAULT 'en',
    timezone         text,
    consent_given_at timestamptz,
    consent_version  text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Auth methods (telegram / email / google)
CREATE TABLE auth_methods (
    id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type       text        NOT NULL,
    value      text        NOT NULL,
    confirmed  boolean     NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_auth_methods_type_value UNIQUE (type, value)
);

-- Contractors (external business entities)
CREATE TABLE contractors (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid       NOT NULL REFERENCES workspaces(id),
    name        text        NOT NULL,
    notes       text,
    archived_at timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_contractors_updated_at
  BEFORE UPDATE ON contractors
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Contractor contacts (phone / email / social — not named persons)
CREATE TABLE contractor_contacts (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid        NOT NULL REFERENCES workspaces(id),
    contractor_id uuid        NOT NULL REFERENCES contractors(id) ON DELETE CASCADE,
    type          text        NOT NULL,
    value         text        NOT NULL,
    label         text,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- Topics (task axis 2: "about what")
CREATE TABLE topics (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid        NOT NULL REFERENCES workspaces(id),
    name         text        NOT NULL,
    is_default   boolean     NOT NULL DEFAULT false,
    visible      boolean     NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Categories (task axis 3: "type of work")
CREATE TABLE categories (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid        NOT NULL REFERENCES workspaces(id),
    name         text        NOT NULL,
    visible      boolean     NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Tasks (core entity, 4 axes)
CREATE TABLE tasks (
    id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id   uuid        NOT NULL REFERENCES workspaces(id),
    title          text        NOT NULL,
    description    text,
    status         text        NOT NULL DEFAULT 'open',
    contractor_id  uuid        REFERENCES contractors(id) ON DELETE SET NULL,
    topic_id       uuid        NOT NULL REFERENCES topics(id),
    category_id    uuid        REFERENCES categories(id) ON DELETE SET NULL,
    parent_task_id uuid        REFERENCES tasks(id) ON DELETE SET NULL,
    due_at         timestamptz,
    deleted_at     timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_tasks_updated_at
  BEFORE UPDATE ON tasks
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- People (executors / participants; optional link to contractor org)
CREATE TABLE people (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid        NOT NULL REFERENCES workspaces(id),
    name          text        NOT NULL,
    contractor_id uuid        REFERENCES contractors(id) ON DELETE SET NULL,
    user_id       uuid        REFERENCES users(id) ON DELETE SET NULL,
    archived_at   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- Task participants (axis 4: who does it)
CREATE TABLE task_participants (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid NOT NULL REFERENCES workspaces(id),
    task_id      uuid NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    person_id    uuid NOT NULL REFERENCES people(id),
    role         text NOT NULL DEFAULT 'executor',
    CONSTRAINT uk_task_participants_task_person UNIQUE (task_id, person_id)
);

-- Notes
CREATE TABLE notes (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid        NOT NULL REFERENCES workspaces(id),
    task_id      uuid        REFERENCES tasks(id) ON DELETE SET NULL,
    content      text        NOT NULL,
    source       text        NOT NULL DEFAULT 'text',
    session_id   text,
    deleted_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Attachments (polymorphic: task or note)
CREATE TABLE attachments (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid        NOT NULL REFERENCES workspaces(id),
    entity_type  text        NOT NULL,
    entity_id    uuid        NOT NULL,
    file_name    text        NOT NULL,
    mime_type    text,
    file_size    bigint,
    storage_path text        NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Time entries
CREATE TABLE time_entries (
    id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id     uuid        NOT NULL REFERENCES workspaces(id),
    task_id          uuid        NOT NULL REFERENCES tasks(id),
    user_id          uuid        NOT NULL REFERENCES users(id),
    started_at       timestamptz NOT NULL,
    ended_at         timestamptz,
    duration_seconds integer,
    notes            text,
    created_at       timestamptz NOT NULL DEFAULT now()
);

-- Reminders
CREATE TABLE reminders (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid        NOT NULL REFERENCES workspaces(id),
    user_id      uuid        NOT NULL REFERENCES users(id),
    entity_type  text,
    entity_id    uuid,
    remind_at    timestamptz NOT NULL,
    status       text        NOT NULL DEFAULT 'pending',
    message      text,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Services / price items
CREATE TABLE services (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid        NOT NULL REFERENCES workspaces(id),
    contractor_id uuid        REFERENCES contractors(id) ON DELETE SET NULL,
    name          text        NOT NULL,
    description   text,
    price         numeric(12,2),
    currency      text        DEFAULT 'RUB',
    unit          text,
    archived_at   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now()
);

-- Knowledge base (RAG + pgvector)
CREATE TABLE kb_entries (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id  uuid        NOT NULL REFERENCES workspaces(id),
    contractor_id uuid        REFERENCES contractors(id) ON DELETE SET NULL,
    title         text        NOT NULL,
    content       text        NOT NULL,
    embedding     vector(1536),
    status        text        NOT NULL DEFAULT 'pending',
    source_type   text,
    source_id     uuid,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_kb_entries_updated_at
  BEFORE UPDATE ON kb_entries
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Bot sessions (dialog state)
CREATE TABLE bot_sessions (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid        NOT NULL REFERENCES workspaces(id),
    user_id      uuid        NOT NULL REFERENCES users(id),
    state        text        NOT NULL DEFAULT 'idle',
    data         jsonb       NOT NULL DEFAULT '{}',
    expires_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_bot_sessions_user_id UNIQUE (user_id)
);

CREATE TRIGGER trg_bot_sessions_updated_at
  BEFORE UPDATE ON bot_sessions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Token usage (OpenAI cost tracking from day 1)
CREATE TABLE token_usage (
    id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id   uuid        NOT NULL REFERENCES workspaces(id),
    operation_type text        NOT NULL,
    model          text        NOT NULL,
    input_tokens   integer,
    output_tokens  integer,
    total_tokens   integer     NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
);

-- =============================================================
-- Indexes
-- =============================================================

-- users
CREATE INDEX idx_users_workspace_id ON users (workspace_id);

-- auth_methods
CREATE INDEX idx_auth_methods_type_value ON auth_methods (type, value);
CREATE INDEX idx_auth_methods_user_id ON auth_methods (user_id);

-- contractors
CREATE INDEX idx_contractors_workspace_id ON contractors (workspace_id);
CREATE INDEX idx_contractors_workspace_archived ON contractors (workspace_id, archived_at);
CREATE INDEX idx_contractors_name_fts ON contractors USING gin (to_tsvector('russian', name));

-- contractor_contacts
CREATE INDEX idx_contractor_contacts_contractor_id ON contractor_contacts (contractor_id);
CREATE INDEX idx_contractor_contacts_workspace_id ON contractor_contacts (workspace_id);

-- topics
CREATE INDEX idx_topics_workspace_id ON topics (workspace_id);
CREATE INDEX idx_topics_workspace_is_default ON topics (workspace_id, is_default);

-- categories
CREATE INDEX idx_categories_workspace_id ON categories (workspace_id);

-- tasks
CREATE INDEX idx_tasks_workspace_status ON tasks (workspace_id, status);
CREATE INDEX idx_tasks_workspace_contractor ON tasks (workspace_id, contractor_id);
CREATE INDEX idx_tasks_workspace_topic ON tasks (workspace_id, topic_id);
CREATE INDEX idx_tasks_workspace_category ON tasks (workspace_id, category_id);
CREATE INDEX idx_tasks_workspace_due_at ON tasks (workspace_id, due_at);
CREATE INDEX idx_tasks_parent_task_id ON tasks (parent_task_id);
CREATE INDEX idx_tasks_fts ON tasks USING gin (
    to_tsvector('russian', title || ' ' || coalesce(description, ''))
);

-- people
CREATE INDEX idx_people_workspace_id ON people (workspace_id);
CREATE INDEX idx_people_contractor_id ON people (contractor_id);
CREATE INDEX idx_people_user_id ON people (user_id);

-- task_participants
CREATE INDEX idx_task_participants_task_id ON task_participants (task_id);
CREATE INDEX idx_task_participants_person_id ON task_participants (person_id);
CREATE INDEX idx_task_participants_workspace_person ON task_participants (workspace_id, person_id);

-- notes
CREATE INDEX idx_notes_workspace_task ON notes (workspace_id, task_id);
CREATE INDEX idx_notes_session_id ON notes (session_id);
CREATE INDEX idx_notes_fts ON notes USING gin (to_tsvector('russian', content));

-- attachments
CREATE INDEX idx_attachments_entity ON attachments (workspace_id, entity_type, entity_id);

-- time_entries
CREATE INDEX idx_time_entries_workspace_task ON time_entries (workspace_id, task_id);
CREATE INDEX idx_time_entries_workspace_user ON time_entries (workspace_id, user_id);

-- reminders
CREATE INDEX idx_reminders_status_remind_at ON reminders (status, remind_at);
CREATE INDEX idx_reminders_workspace_user ON reminders (workspace_id, user_id);

-- services
CREATE INDEX idx_services_workspace_contractor ON services (workspace_id, contractor_id);

-- kb_entries
CREATE INDEX idx_kb_entries_workspace_status ON kb_entries (workspace_id, status);
CREATE INDEX idx_kb_entries_workspace_contractor ON kb_entries (workspace_id, contractor_id);
CREATE INDEX idx_kb_entries_fts ON kb_entries USING gin (
    to_tsvector('russian', title || ' ' || content)
);
CREATE INDEX idx_kb_entries_embedding ON kb_entries
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- bot_sessions
CREATE INDEX idx_bot_sessions_user_id ON bot_sessions (user_id);
CREATE INDEX idx_bot_sessions_expires_at ON bot_sessions (expires_at);

-- token_usage
CREATE INDEX idx_token_usage_workspace_created ON token_usage (workspace_id, created_at);
CREATE INDEX idx_token_usage_workspace_operation ON token_usage (workspace_id, operation_type);


-- =============================================================
-- rollback:
-- DROP TRIGGER IF EXISTS trg_bot_sessions_updated_at ON bot_sessions;
-- DROP TRIGGER IF EXISTS trg_kb_entries_updated_at ON kb_entries;
-- DROP TRIGGER IF EXISTS trg_tasks_updated_at ON tasks;
-- DROP TRIGGER IF EXISTS trg_contractors_updated_at ON contractors;
-- DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
-- DROP TRIGGER IF EXISTS trg_workspaces_updated_at ON workspaces;
-- DROP FUNCTION IF EXISTS set_updated_at();
-- DROP TABLE IF EXISTS token_usage;
-- DROP TABLE IF EXISTS bot_sessions;
-- DROP TABLE IF EXISTS kb_entries;
-- DROP TABLE IF EXISTS services;
-- DROP TABLE IF EXISTS reminders;
-- DROP TABLE IF EXISTS time_entries;
-- DROP TABLE IF EXISTS attachments;
-- DROP TABLE IF EXISTS notes;
-- DROP TABLE IF EXISTS task_participants;
-- DROP TABLE IF EXISTS people;
-- DROP TABLE IF EXISTS tasks;
-- DROP TABLE IF EXISTS categories;
-- DROP TABLE IF EXISTS topics;
-- DROP TABLE IF EXISTS contractor_contacts;
-- DROP TABLE IF EXISTS contractors;
-- DROP TABLE IF EXISTS auth_methods;
-- DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS workspaces;
-- DROP TABLE IF EXISTS processed_updates;
-- DROP EXTENSION IF EXISTS vector;
-- DROP EXTENSION IF EXISTS "uuid-ossp";
-- =============================================================
