-- Seed default data on workspace creation.
-- Generated by Gemini, reviewed by Claude.
-- Patch: renamed tgr_ → trg_ to match project trigger naming convention.

-- rollback:
-- DROP TRIGGER IF EXISTS trg_workspace_seed_defaults ON workspaces;
-- DROP FUNCTION IF EXISTS trg_create_workspace_defaults();
-- DROP FUNCTION IF EXISTS create_workspace_defaults(uuid, text);

-- =============================================================
-- Business logic function
-- =============================================================

CREATE OR REPLACE FUNCTION create_workspace_defaults(
    p_workspace_id uuid,
    p_language     text DEFAULT 'ru'
) RETURNS void AS $$
DECLARE
    v_topic_name  text;
    v_categories  text[];
    v_category    text;
BEGIN
    IF p_language = 'ru' THEN
        v_topic_name := 'Прочее';
        v_categories := ARRAY['Переговоры', 'Продажи', 'Производство', 'Логистика', 'Документы', 'Прочее'];
    ELSE
        v_topic_name := 'Other';
        v_categories := ARRAY['Negotiations', 'Sales', 'Production', 'Logistics', 'Documents', 'Other'];
    END IF;

    -- Idempotent: skip if default topic already exists
    IF NOT EXISTS (
        SELECT 1 FROM topics
        WHERE workspace_id = p_workspace_id AND is_default = true
    ) THEN
        INSERT INTO topics (workspace_id, name, is_default, visible)
        VALUES (p_workspace_id, v_topic_name, true, true);
    END IF;

    -- Idempotent: insert only missing categories
    INSERT INTO categories (workspace_id, name, visible)
    SELECT p_workspace_id, cat, true
    FROM unnest(v_categories) AS cat
    WHERE NOT EXISTS (
        SELECT 1 FROM categories
        WHERE workspace_id = p_workspace_id AND name = cat
    );
END;
$$ LANGUAGE plpgsql;

-- =============================================================
-- Trigger function
-- =============================================================

CREATE OR REPLACE FUNCTION trg_create_workspace_defaults()
RETURNS trigger AS $$
BEGIN
    PERFORM create_workspace_defaults(NEW.id, 'ru');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================
-- Trigger on workspaces
-- =============================================================

CREATE TRIGGER trg_workspace_seed_defaults
    AFTER INSERT ON workspaces
    FOR EACH ROW
    EXECUTE FUNCTION trg_create_workspace_defaults();
